package payments

import (
	"testing"
	"time"

	"github.com/google/uuid"
)

func d(s string) time.Time {
	t, err := time.Parse("2006-01-02", s)
	if err != nil {
		panic(err)
	}
	return t
}

func dp(s string) *time.Time {
	t := d(s)
	return &t
}

// mustID returns a stable, comparable placeholder id derived from name so
// assertions can refer to invoices by a readable label instead of a random
// uuid. Two calls with the same name always return the same id, and
// different names sort by their generated bytes, which is fine — no test
// below depends on a specific id ordering except through the fields it sets
// (PeriodStart, EarliestClassStart) that already determine the order.
func mustID(name string) uuid.UUID {
	return uuid.NewSHA1(uuid.NameSpaceOID, []byte(name))
}

func allocMap(allocs []Allocation) map[uuid.UUID]int64 {
	out := make(map[uuid.UUID]int64, len(allocs))
	for _, a := range allocs {
		out[a.InvoiceID] = a.Amount
	}
	return out
}

// assertInvariant checks the arithmetic invariant every allocation must
// satisfy regardless of the scenario: no đồng is lost or invented.
func assertInvariant(t *testing.T, amount int64, allocs []Allocation, unallocated int64) {
	t.Helper()
	var sum int64
	for _, a := range allocs {
		if a.Amount <= 0 {
			t.Fatalf("zero or negative allocation amount %d for invoice %s", a.Amount, a.InvoiceID)
		}
		sum += a.Amount
	}
	if sum+unallocated != amount {
		t.Fatalf("invariant broken: allocations(%d) + unallocated(%d) = %d, want %d",
			sum, unallocated, sum+unallocated, amount)
	}
}

func TestAllocateExactPaymentClearsOneInvoice(t *testing.T) {
	t.Parallel()
	inv := mustID("inv-1")
	candidates := []Candidate{
		{InvoiceID: inv, PeriodStart: d("2026-01-01"), TotalDue: 100_000, PaidAmount: 0},
	}
	allocs, unallocated := Allocate(100_000, candidates)
	assertInvariant(t, 100_000, allocs, unallocated)
	if got := allocMap(allocs)[inv]; got != 100_000 {
		t.Fatalf("invoice allocation = %d, want 100000", got)
	}
	if unallocated != 0 {
		t.Fatalf("unallocated = %d, want 0", unallocated)
	}
}

func TestAllocateExactPaymentClearsTwoChildrensInvoices(t *testing.T) {
	t.Parallel()
	invA := mustID("inv-a")
	invB := mustID("inv-b")
	candidates := []Candidate{
		{InvoiceID: invA, PeriodStart: d("2026-01-01"), TotalDue: 100_000, PaidAmount: 0},
		{InvoiceID: invB, PeriodStart: d("2026-01-01"), TotalDue: 150_000, PaidAmount: 0},
	}
	allocs, unallocated := Allocate(250_000, candidates)
	assertInvariant(t, 250_000, allocs, unallocated)
	m := allocMap(allocs)
	if m[invA] != 100_000 || m[invB] != 150_000 {
		t.Fatalf("allocations = %+v, want invA=100000 invB=150000", m)
	}
	if unallocated != 0 {
		t.Fatalf("unallocated = %d, want 0", unallocated)
	}
}

func TestAllocateUnderpaymentFillsOlderPeriodFirst(t *testing.T) {
	t.Parallel()
	older := mustID("inv-older")
	newer := mustID("inv-newer")
	candidates := []Candidate{
		{InvoiceID: newer, PeriodStart: d("2026-02-01"), TotalDue: 100_000, PaidAmount: 0},
		{InvoiceID: older, PeriodStart: d("2026-01-01"), TotalDue: 100_000, PaidAmount: 0},
	}
	allocs, unallocated := Allocate(150_000, candidates)
	assertInvariant(t, 150_000, allocs, unallocated)
	m := allocMap(allocs)
	if m[older] != 100_000 {
		t.Fatalf("older period allocation = %d, want fully paid 100000", m[older])
	}
	if m[newer] != 50_000 {
		t.Fatalf("newer period allocation = %d, want partially paid 50000", m[newer])
	}
	if unallocated != 0 {
		t.Fatalf("unallocated = %d, want 0", unallocated)
	}
}

func TestAllocateUnderpaymentWithinOnePeriodSplitsByEarlierClassStart(t *testing.T) {
	t.Parallel()
	earlier := mustID("inv-earlier-class")
	later := mustID("inv-later-class")
	candidates := []Candidate{
		{InvoiceID: later, PeriodStart: d("2026-01-01"), EarliestClassStart: dp("2026-01-10"), TotalDue: 100_000, PaidAmount: 0},
		{InvoiceID: earlier, PeriodStart: d("2026-01-01"), EarliestClassStart: dp("2026-01-01"), TotalDue: 100_000, PaidAmount: 0},
	}
	allocs, unallocated := Allocate(150_000, candidates)
	assertInvariant(t, 150_000, allocs, unallocated)
	m := allocMap(allocs)
	if m[earlier] != 100_000 {
		t.Fatalf("earlier class start allocation = %d, want fully paid 100000", m[earlier])
	}
	if m[later] != 50_000 {
		t.Fatalf("later class start allocation = %d, want partially paid 50000", m[later])
	}
}

// TestAllocateOpeningBalanceAcrossTwoInvoicesSettledBeforeCurrentCharge is the
// core D8 assertion: with just enough money to cover both invoices' opening
// balances and nothing more, the two-pass rule must spread it across both
// opening balances rather than exhausting it on the first invoice's current
// charge.
func TestAllocateOpeningBalanceAcrossTwoInvoicesSettledBeforeCurrentCharge(t *testing.T) {
	t.Parallel()
	invA := mustID("inv-opening-a")
	invB := mustID("inv-opening-b")
	candidates := []Candidate{
		// TotalDue = opening_balance(50000) + current_charge(100000).
		{InvoiceID: invA, PeriodStart: d("2026-01-01"), OpeningBalance: 50_000, TotalDue: 150_000, PaidAmount: 0},
		{InvoiceID: invB, PeriodStart: d("2026-02-01"), OpeningBalance: 50_000, TotalDue: 150_000, PaidAmount: 0},
	}
	allocs, unallocated := Allocate(100_000, candidates)
	assertInvariant(t, 100_000, allocs, unallocated)
	m := allocMap(allocs)
	if m[invA] != 50_000 || m[invB] != 50_000 {
		t.Fatalf("allocations = %+v, want both opening balances settled (50000 each), none touching current charge", m)
	}
}

func TestAllocateNilEarliestClassStartSortsLastInPassTwo(t *testing.T) {
	t.Parallel()
	withDate := mustID("inv-with-class-date")
	noLines := mustID("inv-no-lines")
	candidates := []Candidate{
		{InvoiceID: noLines, PeriodStart: d("2026-01-01"), EarliestClassStart: nil, TotalDue: 100_000, PaidAmount: 0},
		{InvoiceID: withDate, PeriodStart: d("2026-01-01"), EarliestClassStart: dp("2026-01-15"), TotalDue: 100_000, PaidAmount: 0},
	}
	allocs, unallocated := Allocate(50_000, candidates)
	assertInvariant(t, 50_000, allocs, unallocated)
	m := allocMap(allocs)
	if m[withDate] != 50_000 {
		t.Fatalf("invoice with a class start date allocation = %d, want 50000 (filled before the nil one)", m[withDate])
	}
	if _, touched := m[noLines]; touched {
		t.Fatalf("invoice with nil EarliestClassStart must sort last and stay untouched, got %+v", m)
	}
}

func TestAllocateOverpaymentReturnsSurplusAsUnallocated(t *testing.T) {
	t.Parallel()
	inv := mustID("inv-overpaid")
	candidates := []Candidate{
		{InvoiceID: inv, PeriodStart: d("2026-01-01"), TotalDue: 100_000, PaidAmount: 0},
	}
	allocs, unallocated := Allocate(150_000, candidates)
	assertInvariant(t, 150_000, allocs, unallocated)
	if got := allocMap(allocs)[inv]; got != 100_000 {
		t.Fatalf("invoice allocation = %d, want 100000 (capped at outstanding)", got)
	}
	if unallocated != 50_000 {
		t.Fatalf("unallocated = %d, want 50000", unallocated)
	}
}

// TestAllocatePartiallyPaidInvoiceHasOpeningUnpaidReducedCorrectly proves
// opening_unpaid is derived from OpeningBalance-PaidAmount, not the raw
// OpeningBalance: a naive implementation that ignored the prior payment would
// let invoice A absorb the whole payment and starve invoice B, which also
// has an unpaid opening balance.
func TestAllocatePartiallyPaidInvoiceHasOpeningUnpaidReducedCorrectly(t *testing.T) {
	t.Parallel()
	invA := mustID("inv-partially-paid-a")
	invB := mustID("inv-full-opening-b")
	candidates := []Candidate{
		// opening_unpaid = 100000 - 60000 = 40000 (not the raw 100000).
		// outstanding = 140000 - 60000 = 80000; rest_unpaid = 80000-40000 = 40000.
		{InvoiceID: invA, PeriodStart: d("2026-01-01"), OpeningBalance: 100_000, TotalDue: 140_000, PaidAmount: 60_000},
		// Pure opening-balance invoice, nothing paid yet.
		{InvoiceID: invB, PeriodStart: d("2026-02-01"), OpeningBalance: 50_000, TotalDue: 50_000, PaidAmount: 0},
	}
	allocs, unallocated := Allocate(70_000, candidates)
	assertInvariant(t, 70_000, allocs, unallocated)
	m := allocMap(allocs)
	if m[invA] != 40_000 {
		t.Fatalf("invoice A allocation = %d, want 40000 (its reduced opening_unpaid)", m[invA])
	}
	if m[invB] != 30_000 {
		t.Fatalf("invoice B allocation = %d, want 30000 (the remainder after A's opening_unpaid)", m[invB])
	}
}

// TestAllocateNegativeAdjustmentTotalNeverYieldsNegativeAllocation proves a
// discount large enough to push total_due below opening_balance never lets
// opening_unpaid (or rest_unpaid) go negative or exceed the invoice's real
// outstanding.
func TestAllocateNegativeAdjustmentTotalNeverYieldsNegativeAllocation(t *testing.T) {
	t.Parallel()
	inv := mustID("inv-negative-adjustment")
	candidates := []Candidate{
		// current_charge=0, adjustment_total=-20000: total_due(80000) < opening_balance(100000).
		{InvoiceID: inv, PeriodStart: d("2026-01-01"), OpeningBalance: 100_000, TotalDue: 80_000, PaidAmount: 0},
	}
	allocs, unallocated := Allocate(100_000, candidates)
	assertInvariant(t, 100_000, allocs, unallocated)
	if got := allocMap(allocs)[inv]; got != 80_000 {
		t.Fatalf("invoice allocation = %d, want 80000 (capped at outstanding, never the raw opening_balance)", got)
	}
	if unallocated != 20_000 {
		t.Fatalf("unallocated = %d, want 20000", unallocated)
	}
}

func TestAllocateZeroAmountAllocationsAreOmittedEntirely(t *testing.T) {
	t.Parallel()
	alreadySettled := mustID("inv-already-settled")
	stillOwed := mustID("inv-still-owed")
	candidates := []Candidate{
		// outstanding = 0: already fully paid, must never appear in allocs.
		{InvoiceID: alreadySettled, PeriodStart: d("2026-01-01"), TotalDue: 100_000, PaidAmount: 100_000},
		{InvoiceID: stillOwed, PeriodStart: d("2026-02-01"), TotalDue: 100_000, PaidAmount: 0},
	}
	allocs, unallocated := Allocate(50_000, candidates)
	assertInvariant(t, 50_000, allocs, unallocated)
	if len(allocs) != 1 {
		t.Fatalf("allocs = %+v, want exactly one row (the already-settled invoice must be omitted, not zeroed)", allocs)
	}
	if allocs[0].InvoiceID != stillOwed || allocs[0].Amount != 50_000 {
		t.Fatalf("allocs[0] = %+v, want {stillOwed 50000}", allocs[0])
	}
}

// TestAllocateInvariantHoldsAcrossRandomizedAmounts exercises the
// sum(allocations)+unallocated==amount invariant against a wider spread of
// payment sizes over a realistic multi-invoice, multi-period candidate set —
// belt-and-braces on top of the invariant already checked inside every case
// above.
func TestAllocateInvariantHoldsAcrossRandomizedAmounts(t *testing.T) {
	t.Parallel()
	candidates := []Candidate{
		{InvoiceID: mustID("rand-a"), PeriodStart: d("2026-01-01"), OpeningBalance: 30_000, TotalDue: 130_000, PaidAmount: 10_000},
		{InvoiceID: mustID("rand-b"), PeriodStart: d("2026-01-01"), EarliestClassStart: dp("2026-01-05"), TotalDue: 90_000, PaidAmount: 0},
		{InvoiceID: mustID("rand-c"), PeriodStart: d("2026-02-01"), TotalDue: 200_000, PaidAmount: 200_000},
	}
	for _, amount := range []int64{0, 1, 40_000, 220_000, 421_000, 1_000_000} {
		allocs, unallocated := Allocate(amount, candidates)
		assertInvariant(t, amount, allocs, unallocated)
		for _, a := range allocs {
			if a.InvoiceID == mustID("rand-c") {
				t.Fatalf("already fully paid invoice must never receive an allocation, got amount=%d", amount)
			}
		}
	}
}
